### ISSUE TITLE
Error: true is not a PostCSS plugin

### ISSUE THREAD

**Issue by creage** [webpack-contrib/postcss-loader#482]
- Operating System: Windows
- Node Version: 14.9.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- postcss-loader Version: 4.0.2
- autoprefixer: **10.0.0**

### Expected Behavior
Having `autoprefixer` plugin defined in config should process styles correctly.

### Actual Behavior
Trying to run `webpack` fails with exception:
```
ERROR in node_modules/prismjs/plugins/line-numbers/prism-line-numbers.css
Module build failed (from node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from node_modules/postcss-loader/dist/cjs.js):
Error: true is not a PostCSS plugin
    at Processor.normalize (node_modules\postcss\lib\processor.js:168:15)
    at new Processor (node_modules\postcss\lib\processor.js:52:25)
    at postcss (node_modules\postcss\lib\postcss.js:55:10)
    at Object.loader (node_modules\postcss-loader\dist\index.js:94:41)
    at node_modules\webpack\lib\NormalModule.js:316:20
    at node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (node_modules\postcss-loader\dist\index.js:103:7)
 @ ./components/Page/controls/WzcConfiguration/ConfigPreview.js 6:0-61
 @ ./components/Page/controls/WzcConfiguration/EffectiveConfiguration.js
 @ ./components/Page/Dependencies.js
 @ ./App.exports.js
 @ ./App.js
 @ dll App
```
Returning `autoprefixer` to **v9.8.6** solves the problem, so I'm not sure who should address it.

### Code

```js
...
module: {
    rules: [
        {
            test: /\.css$/,
            use: [
                MiniCssExtractPlugin.loader,
                {
                    loader: 'css-loader',
                    options: {
                        importLoaders: 1
                    }
                },
                {
                    loader: 'postcss-loader',
                    options: {
                        postcssOptions: {
                            plugins: ['autoprefixer']
                        }
                    }
                }
            ]
        }
    ]
}
...
```

**Comment by evilebottnawi** [comment]
Update postcss to `8` version
