### ISSUE TITLE
Unnecessary semicolon error,when build with webpack5 and antd

### ISSUE THREAD

**Issue by X-neuron** [webpack-contrib/postcss-loader#491]
- Operating System:win10
- Node Version:14.12.0
- NPM Version:6.14.8
- webpack Version:5.0.0-rc.3
- postcss-loader Version:4.0.3

```js
ERROR in ./node_modules/antd/es/style/index.less
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:25) E:\project\antdWebpack5Test\node_modules\antd\es\style\index.less Unnecessary semicolon

> 1 | @import './themes/index';
    |                         ^
  2 | @import './core/index';
  3 |

 @ ./node_modules/antd/es/button/style/index.js 1:0-32
 @ ./src/CountBtn.js 1:0-30
 @ ./src/app.jsx 7:0-34 9:71-79
 @ ./src/index.jsx 7:0-24 12:35-38
```

### How Do We Reproduce?
https://github.com/X-neuron/antdWebpack5Test

**Comment by evilebottnawi** [comment]
You can't use `CSS` inside JS, read the error message, `postcss-loader` try to parse JS file, you need search the problem in the configuration

**Comment by X-neuron** [comment]
thanks very much~

**Comment by X-neuron** [comment]
repo is here：
https://github.com/X-neuron/webpack5antdtest

when  disable the poss-loader ，after "npm run dev/build" it works fine, can see the correct result. so this can infer less-loader and css-loader works fine and include/ exclude logic maybe right.


in webpack/webpack.config.js
```
const getStyleLoaders = (cssOptions, preProcessor) => {
    const loaders = [
      isEnvDevelopment && require.resolve("style-loader"),
      isEnvProduction && {
        loader: MiniCssExtractPlugin.loader,
        // css is located in `static/css`, use '../../' to locate index.html folder
        // in production `paths.publicUrlOrPath` can be a relative path
        options: paths.publicUrlOrPath.startsWith(".")
          ? { publicPath: "../../"}
          : { },
      },
      {
        loader: require.resolve("css-loader"),
        options: cssOptions,
      },
      false && {
        loader: "postcss-loader",
        options: {
          // Necessary for external CSS imports to work
          // https://github.com/facebook/create-react-app/issues/2677
          postcssOptions:{
            // Options for PostCSS as we reference these options twice
            // Adds vendor prefixing based on your specified browser support in
            ident: "postcss",
            plugins: [
              require("postcss-flexbugs-fixes"),
              require("postcss-preset-env")({
                autoprefixer: {
                  flexbox: "no-2009",
                },
                stage: 3,
              }),
              // Adds PostCSS Normalize as the reset css with default options,
              // so that it honors browserslist config in package.json
              // which in turn let's users customize the target behavior as per their needs.
              postcssNormalize(),
            ],
          },
          sourceMap: isEnvProduction ? shouldUseSourceMap : isEnvDevelopment,
        },
      },
    ].filter(Boolean);
    if (preProcessor) {
      loaders.push(
        {
          loader: require.resolve("resolve-url-loader"),
          options: {
            sourceMap: isEnvProduction ? shouldUseSourceMap : isEnvDevelopment,
          },
        },
        typeof preProcessor === "string"
          ? {
            loader: require.resolve(preProcessor),
            options: {
              sourceMap: isEnvProduction
                ? shouldUseSourceMap
                : isEnvDevelopment,
            },
          }
          : preProcessor,
      );
    }
    // console.log(loaders)
    return loaders;
  };
```

but when enable the poss-loader，error encountered， I'm not sure which loader problem is

```
(3:0) E:\project\antdwebpack5test\index.less Unnecessary curly bracket

  1 | /* stylelint-disable at-rule-empty-line-before,at-rule-name-space-after,at-rule-no-unknown */
  2 | /* stylelint-disable no-duplicate-selectors */
> 3 | /* stylelint-disable */
    |                                 ^
  4 | /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
  5 | .menu :global(.anticon) {

    at processResult (E:\project\antdwebpack5test\node_modules\webpack\lib\NormalModule.js:576:19)
    at E:\project\antdwebpack5test\node_modules\webpack\lib\NormalModule.js:669:5
    at E:\project\antdwebpack5test\node_modules\loader-runner\lib\LoaderRunner.js:397:11
    at E:\project\antdwebpack5test\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (E:\project\antdwebpack5test\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (E:\project\antdwebpack5test\node_modules\postcss-loader\dist\index.js:101:7)
 @ ./src/components/SelectLang/index.jsx 3:91-124 5:50-61 7:609-624
 @ ./src/app.jsx 4:163-211 5:1080-1090
 @ ./src/index.jsx 4:44-67 13:149-152

```

So can we treat it as a postcss-loader loader's bug, can not work with less-loader v7?

**Comment by evilebottnawi** [comment]
It is problem with postcss parser, not with postcss-loader

**Comment by X-neuron** [comment]
thanks so much~
