### ISSUE TITLE
Unable to build after upgrade from version `7.1.0` to `7.2.4` with `@svgr/webpack`

### ISSUE THREAD

**Issue by annidai** [webpack-contrib/postcss-loader#645]
### Bug report

I'm seeing a weird issue after I upgrade `postcss-loader` from version `7.1.0` to `7.2.4`.
My build starts to fail due to the following:
```
Module build failed (from ./node_modules/@svgr/webpack/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'getSourceFile')
   at getValidSourceFile (/node_modules/typescript/lib/typescript.js:169214:38)
    at Object.getEmitOutput (/node_modules/typescript/lib/typescript.js:169713:30)
    at getOutput (/node_modules/ts-node/src/index.ts:736:32)
    at Object.compile (/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .js] (/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:[19])
```

I also tested with other 7.2.+ builds, all have the same issue.

### Actual Behavior
See above

### Expected Behavior
Should be able to build.

### How Do We Reproduce?
I spot this when doing dependencies upgrade for a project.
I have @svgr/webpack (version 7.0.0) configured as SVG loader in `webpack.config.js`
```
     {
        test: /\.svg$/,
        use: ['@svgr/webpack'],
      },
```

The build was working properly witih `postcss-loader 7.1.0`.

### Please paste the results of `npx webpack info` here, and mention other relevant information

```
 $ npx webpack info       
  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.69 GB / 32.00 GB
  Binaries:
    Node: 16.18.1 - ~/.volta/tools/image/node/16.18.1/bin/node
    Yarn: 1.22.19 - ~/Development/eblock-web/node_modules/.bin/yarn
    npm: 9.6.4 - ~/.volta/tools/image/npm/9.6.4/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Edge: 112.0.1722.39
    Firefox: 109.0
    Safari: 16.4
  Packages:
    babel-loader: 9.1.2 => 9.1.2 
    copy-webpack-plugin: 11.0.0 => 11.0.0 
    css-loader: 6.7.3 => 6.7.3 
    eslint-import-resolver-webpack: 0.13.2 => 0.13.2 
    file-loader: 6.2.0 => 6.2.0 
    html-webpack-plugin: 5.5.0 => 5.5.0 
    postcss-loader: 7.1.0 => 7.1.0 
    resolve-url-loader: 5.0.0 => 5.0.0 
    sass-loader: 13.2.2 => 13.2.2 
    style-loader: 3.3.2 => 3.3.2 
    swc-loader: 0.2.3 => 0.2.3 
    ts-loader: 9.4.2 => 9.4.2 
    unused-webpack-plugin: 2.4.0 => 2.4.0 
    url-loader: 4.1.1 => 4.1.1 
    webpack: 5.79.0 => 5.79.0 
    webpack-bundle-analyzer: 4.8.0 => 4.8.0 
    webpack-cli: 5.0.1 => 5.0.1 
    webpack-dev-server: 4.13.2 => 4.13.2 
    webpack-hot-middleware: 2.25.3 => 2.25.3 
```

**Comment by alexander-akait** [comment]
Please create reproducible test repo, sorry it is impossible to say what is wrong without it

**Comment by annidai** [comment]
I'll reopen it if I can create a reproducible test repo for this.

**Comment by alexander-akait** [comment]
Thank you, feel  free to ping me
